### ISSUE TITLE
Adapt the UKF & NearestNeighborAssociation to custom detecion model

### ISSUE THREAD

**Issue by Alex-Beh** [koide3/monocular_people_tracking#3]
Hello, thanks for sharing this great project. I would like to adapt the ukf and nearest neighbor association code from this project to the my custom detection model such as yolov3 with a RGBD camera that will provide the detecion result in term of x & y relative to camera frame. 

However, i don't totally understand the code and open this issue to request help. So far my conclusion is
1. I can reuse the unscented_kalman_filter.hpp code. I do need to change anything on this code.
2. I need to convert the [observation.hpp](https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/include/monocular_people_tracking/observation.hpp) adapt to my detection results.

Question 1:
It mentioned [this function](https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/include/kkl/alg/data_association.hpp#L20) is specialized for Tracker and Observation. Do you mean this [function](https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/include/monocular_people_tracking/association_distance.hpp#L24)?

Question 2:
If my detection model already provide me the position x and position y information, then I don't need the [Projection](https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/src/person_tracker.cpp#L84) class? My understanding on the Projection class is it transform the 2D detection result from image into 3D coordiante using the intrinsic camera matrix. It is pinhole camera projection function that mentioned in the paper, right? 

Question 3:
What is the role of [NelderMeadSolver](https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/src/person_tracker.cpp#L159) in the code? How should I change it if I not using the Projection class?

**Comment by koide3** [comment]
1. Yes, it is the function to define the distance between each tracklet (individual tracker) and observation. At some point, I changed the the ```NearestNeighborAssociation``` class so it takes a functor rather than using the the specialized function, and thus the comment is now obsolete.
2. Yes, your understanding is correct. If you can directly obtain XY positions, you don't need the ```Projection``` class. We assumed the pinhole projection model in this work.
3. The ```NelderMeadSolver``` was used for UKF state initialization (initial mean estimation); it finds the person's position and height that minimizes the reprojection error for the given observation. You don't need to use it because you can simply give the XY position given by the depth camera to the UKF constructor.

https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/src/person_tracker.cpp#L25

**Comment by Alex-Beh** [comment]
Hello, thanks for your reply. 

**Question 1:**
The functor you mentioned is [this](https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/include/monocular_people_tracking/association_distance.hpp#L24)? May I know the intuition behind [this line](https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/include/monocular_people_tracking/association_distance.hpp#L28)?

**Question 3:**
So I should change [this line](https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/src/person_tracker.cpp#L19)
`mean.head<3>() = estimate_init_state(track_system, neck_ankle);` 
**to**
`mean.head<3>() = Eigen::Vector3f(x,y,0);
`
???

**Question 4:**
How should I change [this function](https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/src/track_system.cpp#L6) accordingly to my usecase? Can you give me some hint?

**Comment by koide3** [comment]
1. Yes, it is. That line filters out invalid joint detection that have x=y=0.
3. Here, the UKF state is ```[pos_x, pos_y, height, vel_x, vel_y]``` of a person. Thus, you should put ```[x, y, initial guess for height (e.g., 1.6~1.7 m)]``` in ```mean```.
4. I think you can simply calculate expected 3D positions of neck and ankle positions from the ```state``` vector, and return them as expected observations.

**Comment by Alex-Beh** [comment]
Thanks for your great hints. I think I will just do a 2D tracking with the UKF state [pos_x, pos_y, vel_x, vel_y].

I have some questions on the is_valid() funtion.

For this [is_valid()](https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/include/monocular_people_tracking/person_tracker.hpp#L74) function, it is used to publish the track msg if the detection results that associate with this track id is higher than the validation_correction_count?

But how about this [is_valid()](https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/include/monocular_people_tracking/observation.hpp#L76) function? I do not really understand the effect of static_cast<bool> on a <Eigen::Vector2f>?

Another question is why use [Eigen::Vector2f::Zero()](https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/src/person_tracker.cpp#L43) in the prediction stage of UKF? Why no predict from the constant velocity model than mentioned in the paper?

**Comment by Alex-Beh** [comment]
@koide3 Friendly ping. I guess for the last question why use Eigen::Vector2f::Zero() in the prediction stage is becasue that variable is not been used in the [function called](https://github.com/koide3/monocular_people_tracking/blob/d2938a7c09004a3d895417c434845d1dadd9863d/include/monocular_people_tracking/track_system.hpp#L73).

Do you have any rosbag file for me to do the debugging?

**Comment by koide3** [comment]
> For this is_valid() function, it is used to publish the track msg if the detection results that associate with this track id is higher than the validation_correction_count?

Yes, it is a common technique for track initialization to suppress short-life tracks caused by false-positives appear momentarily.

> But how about this is_valid() function? I do not really understand the effect of static_cast on a Eigen::Vector2f?

That ```is_valid()``` see if an observation has a neck data (it's ```boost::optional```) to check its validity. Any OpenPose detection without neck joint will not be associated with tracks.

> I guess for the last question why use Eigen::Vector2f::Zero() in the prediction stage is becasue that variable is not been used in the function called.

Yes, your understanding is correct.

> Do you have any rosbag file for me to do the debugging?

Probably I'll put a sample rosbag next week.

**Comment by Alex-Beh** [comment]
@koide3 Thanks. Looking forwards to your rosbag file :)

**Comment by koide3** [comment]
Sorry, I was a bit busy last weeks and forgot that. I'll upload a sample rosbag soon...

**Comment by koide3** [comment]
Sorry, I was still busy this week and couldn't take a sample data, but I think I'll be able to have time to take and upload a sample data by the next weekend.

**Comment by koide3** [comment]
I uploaded a sample rosbag. Please see the following wiki page:
https://github.com/koide3/monocular_person_following/wiki/Quick-test-with-sample-rosbag
